[kiali-server] adding ability to configure extra environment variables
kiali/helm-charts pull request #263
Opened 2024-05-21 16:17 UTC by jdgeisler

We noticed CPU throttling in Kiali due to GOMAXPROCS not being configured correctly. In order to fix this, we had to set the GOMAXPROCS environment variable in Kiali, however the helm chart currently does not have the ability to set additional environment variables.

This MR is adding the `extraEnvs` field to the kiali-server helm chart so that extra environment variables can be set in Kiali in a flexible way. An example of configuring this is below:

```
extraEnvs:
  - name: GOMAXPROCS
    value: "2"
  - name: test
    value: "true"
```

It then templates into the deployment like this:

```
env:
- name: ACTIVE_NAMESPACE
   valueFrom:
     fieldRef:
       fieldPath: metadata.namespace
- name: LOG_LEVEL
   value: "info"
- name: LOG_FORMAT
   value: "text"
- name: LOG_TIME_FIELD_FORMAT
   value: "2006-01-02T15:04:05Z07:00"
- name: LOG_SAMPLER_RATE
   value: "1"
- name: GOMAXPROCS
   value: "2"
- name: test
   value: "true"
```

By default, it is set to `extraEnvs: []` so that no extra environment variables are passed.

2024-05-21 17:31 UTC, jshaughn commented
Hi @jdgeisler , thanks for the submission!  Would you mind [creating an issue](https://github.com/kiali/kiali/issues/new/choose) to go with it, that helps us keep track of things.

2024-05-21 17:53 UTC, jmazzitelli commented
Yes. What @jshaughn says. Here's the contribution readme where we document this: https://github.com/kiali/kiali/blob/master/CONTRIBUTING.md#making-a-change

The reason why we don't like people submitting PRs without an issue is because we lose the ability to dialogue with the community about the feature before you spend time working on a PR. For example, the server helm chart is merely a [convenience installer for Kiali](https://kiali.io/docs/installation/installation-guide/install-with-helm/#introduction) - the suggested install method is the [operator](https://kiali.io/docs/installation/installation-guide/install-with-helm/#install-with-operator). As such, any changes that go into the server helm charts must also go into the operator so we retain feature parity (the server helm chart should not have additional features that the operator does not).

Please see the developer checklist for the different touch points a feature like this is going to need to update before we merge it into any release: 
* [Are You Altering a Kiali Server Resource?](https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#are-you-altering-a-kiali-server-resource)
* [Are You Altering a Kiali Server Configuration Setting?](https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#are-you-altering-a-kiali-server-configuration-setting)

2024-05-21 18:00 UTC, jmazzitelli requested changes

2024-05-21 18:00 UTC, jmazzitelli commented on kiali-server/templates/deployment.yaml
> +        {{- with .Values.deployment.extraEnvs }}
For legacy reasons, all settings are snake_case, not camelCase. To remain consistent across all Kiali settings in the Kiali CR and server helm charts, use snake_case for any new settings.

Also to remain consistent with other analogous settings (such as existing settings of [`additional_labels`](https://github.com/kiali/helm-charts/blob/v1.84.0/kiali-server/values.yaml#L61) and [`additional_service_yaml`](https://github.com/kiali/helm-charts/blob/v1.84.0/kiali-server/values.yaml#L44)), extra_envs should be renamed `additional_envs`.

2024-05-21 18:00 UTC, jmazzitelli commented on kiali-server/values.yaml
> +  extraEnvs: []
For legacy reasons, all settings are snake_case, not camelCase. To remain consistent across all Kiali settings in the Kiali CR and server helm charts, use snake_case for any new settings.

Also to remain consistent with other analogous settings (such as existing settings of [`additional_labels`](https://github.com/kiali/helm-charts/blob/v1.84.0/kiali-server/values.yaml#L61) and [`additional_service_yaml`](https://github.com/kiali/helm-charts/blob/v1.84.0/kiali-server/values.yaml#L44)), extra_envs should be renamed `additional_envs`.

2024-05-21 18:04 UTC, jmazzitelli commented on kiali-server/templates/deployment.yaml
> +        {{- with .Values.deployment.extraEnvs }}
Also, [as per the developer checklist mentioned earlier](https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#are-you-altering-a-kiali-server-configuration-setting), "Ensure each group of settings are alphabetically sorted in all the files where the new setting was added."

So this new `additional_envs` should be placed on the line before [`additional_service_yaml` found here](https://github.com/kiali/helm-charts/blob/v1.84.0/kiali-server/values.yaml#L44).

2024-05-21 18:07 UTC, jdgeisler commented
Hey @jshaughn and @jmazzitelli 

Thank you for the information. I have created the issue https://github.com/kiali/kiali/issues/7375

If this is okay, I can go ahead and work on the operator PR too.

2024-05-22 13:25 UTC, jshaughn commented
Closing as the issue was resolved in v1.83.

2024-05-22 13:25 UTC, closed without merging