[multi-cluster] Add permissions needed for the "Mesh" page
kiali/helm-charts pull request #30
Opened 2021-01-15 22:05 UTC by israel-hdez

Related kiali/kiali#1833
Related kiali/kiali#3409
Related kiali/kiali-operator#235

2021-01-15 22:36 UTC, jmazzitelli requested changes

2021-01-15 22:36 UTC, jmazzitelli commented on kiali-server/templates/rolebinding-controlplane.yaml
> +  {{- end }}
this looks like a remnant from a copy-n-paste - i think it should be deleted.
```suggestion
```

2021-01-18 17:27 UTC, israel-hdez commented
@jmazzitelli I removed the offending line. Also, I just tested and all looks good on my end.

2021-01-18 17:55 UTC, jmazzitelli approved these changes
lgtm

2021-01-18 20:40 UTC, merged