Update ingress.yaml to fix apiVersion if condition
kiali/helm-charts pull request #306
Opened 2024-12-23 15:40 UTC by diwap

2024-12-23 15:53 UTC, jmazzitelli commented
Please provide a github issue following the community contribution guidelines: 

https://github.com/kiali/kiali/blob/master/CONTRIBUTING.md#making-a-change

Explain the bug you think you found and how you think it should be corrected. The Kiali maintainers can then have a dialogue with you before you spend time on code fixes that may or may not be needed.

Also note there is more than just the helm charts - bug fixes likely also need to be fixed in the operator (unless the operator also doesn't have the same bug - this is one reason we ask that community members create an issue so we can have a discussion about the issue prior to PRs being submitted).

2024-12-23 15:56 UTC, jmazzitelli commented
Note, in the github issue you will create, I will ask about this https://github.com/kiali/helm-charts/pull/95 (that `/Ingress` was ADDED in a previous release due to the reasons mentioned in that issue). So in your github issue, please address that PR #95 and why you think it was wrong to be added 3 years ago.

2024-12-23 15:59 UTC, jmazzitelli requested changes
This partially reverts PR #95 (it changes one of the if-conditions but not the other one).

Do not merge until we have grounds for reverting PR #95.

2025-01-13 16:45 UTC, jmazzitelli commented
> Do we have an issue for this? If not we will soon close this PR.

There was no issue created, and the description of this PR is empty; thus we have no use-case or reason for partially reverting an older PR. I would close this.

2025-01-13 16:53 UTC, jshaughn commented
Closing, can re-open with a relevant issue.

2025-01-13 16:53 UTC, closed without merging